// Generated by CopilotConnectorWorkflow. Replace this file to integrate a live data source.
// Default implementation reads pre-enhanced records from a local JSONL file.

import * as fs from 'fs';
import * as path from 'path';

export interface ExternalItem {
  id: string;
  acl: Array<{ accessType: 'grant' | 'deny'; type: 'user' | 'group' | 'everyone' | 'everyoneExceptGuests' | 'externalGroup'; value: string }>;
  properties: Record<string, unknown>;
  content: { type: 'text' | 'html'; value: string };
}

export interface DataSource {
  fetchItems(): AsyncIterable<ExternalItem>;
}

/** Reads enhanced-items.jsonl produced by the workflow. */
export class JsonlDataSource implements DataSource {
  constructor(private readonly filePath: string, private readonly aclMode: 'everyone' | 'everyoneExceptGuests' | 'none' = 'everyone') {}

  async *fetchItems(): AsyncIterable<ExternalItem> {
    const abs = path.isAbsolute(this.filePath) ? this.filePath : path.resolve(process.cwd(), this.filePath);
    if (!fs.existsSync(abs)) throw new Error(`Data source file not found: ${abs}`);
    const lines = fs.readFileSync(abs, 'utf-8').split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const item = JSON.parse(trimmed) as Partial<ExternalItem> & { content?: { value?: string } };
      const acl = this.aclMode === 'none' ? (item.acl || []) : [{ accessType: 'grant' as const, type: this.aclMode, value: this.aclMode }];
      const out: ExternalItem = {
        id: String(item.id),
        acl,
        properties: (item.properties || {}) as Record<string, unknown>,
        content: {
          type: (item.content?.type as 'text' | 'html') || 'text',
          value: String(item.content?.value ?? ''),
        },
      };
      yield out;
    }
  }
}

export function defaultDataSource(): DataSource {
  const aclMode = (process.env.ACL_MODE as 'everyone' | 'everyoneExceptGuests' | 'none') || 'everyone';
  const dataPath = process.env.DATA_SOURCE_PATH || './data/enhanced-items.jsonl';
  return new JsonlDataSource(dataPath, aclMode);
}
