import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { JobRecord, JobConfig, StepName, StepRecord, ALL_STEPS, PipelineDetection } from './types';
import { hashDataset, hashEvalSetFile } from './canonical-hash';
import { detectDatasetShape } from './dataset-shape-detect';

const WORKSPACE_ROOT = path.resolve(__dirname, '..', 'workspace', 'jobs');

export function workspaceRoot(): string {
  if (!fs.existsSync(WORKSPACE_ROOT)) fs.mkdirSync(WORKSPACE_ROOT, { recursive: true });
  return WORKSPACE_ROOT;
}

export function newJobId(): string {
  const t = new Date();
  const stamp = `${t.getFullYear()}${pad(t.getMonth() + 1)}${pad(t.getDate())}-${pad(t.getHours())}${pad(t.getMinutes())}${pad(t.getSeconds())}`;
  const suffix = crypto.randomBytes(3).toString('hex');
  return `${stamp}-${suffix}`;
}

function pad(n: number): string { return n < 10 ? `0${n}` : String(n); }

export function jobDir(jobId: string): string {
  return path.join(workspaceRoot(), jobId);
}

export function createJob(config: JobConfig): JobRecord {
  applyConfigDefaults(config);
  validateConfig(config);
  applyPipelineDetection(config);
  const id = newJobId();
  const dir = jobDir(id);
  fs.mkdirSync(dir, { recursive: true });
  const now = new Date().toISOString();
  const steps = {} as Record<StepName, StepRecord>;
  for (const name of ALL_STEPS) steps[name] = { name, status: 'pending' };
  let datasetHash: string | undefined;
  try {
    datasetHash = hashDataset(config.dataset, config.extensions).hash;
  } catch {
    // dataset hash is best-effort at job creation; jobs created before hashing was added still work.
  }
  const job: JobRecord = {
    id,
    createdAt: now,
    updatedAt: now,
    status: 'pending',
    config,
    steps,
    workspace: dir,
    datasetHash,
  };
  saveJob(job);
  // Persist a copy of the detection result to a dedicated audit file so it
  // survives job-record schema changes and is greppable.
  if (config.pipelineDetection) {
    const auditDir = path.join(dir, '00-shape-detect');
    fs.mkdirSync(auditDir, { recursive: true });
    fs.writeFileSync(
      path.join(auditDir, 'shape-detect.json'),
      JSON.stringify(config.pipelineDetection, null, 2),
      'utf-8',
    );
  }
  return job;
}

/**
 * Fill in the connector fields the workflow can derive on its own so the GUI
 * can present them as optional. Description, connectorId, and connectorName are
 * auto-generated from the dataset folder name when the caller leaves them blank
 * (or supplies a value too short to pass validation). Explicit, valid values
 * provided by the caller are always preserved untouched — this only ever fills
 * gaps, so existing callers/fixtures that pass all fields are unaffected.
 */
export function applyConfigDefaults(config: JobConfig): void {
  const datasetBase = config.dataset
    ? path.basename(String(config.dataset).replace(/[\\/]+$/, ''))
    : '';

  if (!config.connectorName || !config.connectorName.trim()) {
    const pretty = datasetBase.replace(/[._-]+/g, ' ').replace(/\s+/g, ' ').trim();
    config.connectorName = pretty ? toTitleCase(pretty) : 'My Connector';
  }

  if (!config.connectorId || !/^[a-zA-Z0-9]{3,128}$/.test(config.connectorId)) {
    let base = (alnum(config.connectorId) || alnum(config.connectorName) || alnum(datasetBase)).toLowerCase();
    if (base.length < 3) base = `${base}connector`;
    config.connectorId = base.slice(0, 128);
  }

  if (!config.description || config.description.trim().length < 10) {
    const subject = config.connectorName || config.connectorId || 'this dataset';
    config.description = `Copilot connector for the ${subject} dataset, auto-generated by the Copilot Connector Workflow.`;
  }
}

function alnum(s: string | undefined): string {
  return (s || '').replace(/[^a-zA-Z0-9]/g, '');
}

function toTitleCase(s: string): string {
  return s.replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1));
}

/**
 * Decide whether to auto-flip noEnhance based on dataset shape. Precedence:
 *   forceEnhance > noEnhance (explicit) > autoDetectPipeline > default
 *
 * Conservative behavior: only flips to noEnhance=true when the detector is
 * confident the dataset is text-rich AND effectively single-schema. The
 * detection result is recorded as evidence whenever the detector runs.
 */
function applyPipelineDetection(config: JobConfig): void {
  // Explicit user choice wins; never overrule. forceEnhance is the strongest
  // signal — the user wants the enhancer no matter what.
  if (config.forceEnhance) {
    if (config.noEnhance) {
      throw new Error('forceEnhance and noEnhance are mutually exclusive');
    }
    config.noEnhance = false;
    return;
  }
  if (config.noEnhance !== undefined) {
    // User has explicitly opted in or out of enhancement.
    return;
  }
  if (!config.autoDetectPipeline) {
    return;
  }

  let detection;
  try {
    detection = detectDatasetShape(config.dataset, config.extensions);
  } catch (e) {
    // Detection is best-effort; never block job creation.
    const message = e instanceof Error ? e.message : String(e);
    config.pipelineDetection = {
      recommendation: 'enhance',
      appliedNoEnhance: false,
      recordsSampled: 0,
      filesScanned: 0,
      distinctSchemas: 0,
      dominantSchemaShare: 0,
      dominantSchema: [],
      textRichFields: [],
      reason: `detection failed: ${message}`,
    };
    return;
  }

  const appliedNoEnhance = detection.recommendation === 'identity';
  if (appliedNoEnhance) {
    config.noEnhance = true;
  }
  config.pipelineDetection = {
    recommendation: detection.recommendation,
    appliedNoEnhance,
    recordsSampled: detection.recordsSampled,
    filesScanned: detection.filesScanned,
    distinctSchemas: detection.distinctSchemas,
    dominantSchemaShare: detection.dominantSchemaShare,
    dominantSchema: detection.dominantSchema,
    textRichFields: detection.textRichFields,
    reason: detection.reason,
  } satisfies PipelineDetection;
}

/**
 * Compute and record evalSetHash from this job's Step 1 output, if not already
 * set. Called by Step 1 (and lazily by tools that need the hash on legacy jobs).
 */
export function ensureEvalSetHash(job: JobRecord): string | undefined {
  if (job.evalSetHash) return job.evalSetHash;
  const sidecar = path.join(job.workspace, '01-evalgen', 'eval.evalgen.json');
  if (!fs.existsSync(sidecar)) return undefined;
  job.evalSetHash = hashEvalSetFile(sidecar).hash;
  saveJob(job);
  return job.evalSetHash;
}

export function saveJob(job: JobRecord): void {
  job.updatedAt = new Date().toISOString();
  const file = path.join(job.workspace, 'job.json');
  fs.writeFileSync(file, JSON.stringify(job, null, 2), 'utf-8');
}

export function loadJob(jobId: string): JobRecord | undefined {
  const file = path.join(jobDir(jobId), 'job.json');
  if (!fs.existsSync(file)) return undefined;
  return JSON.parse(fs.readFileSync(file, 'utf-8')) as JobRecord;
}

export function listJobs(): JobRecord[] {
  const root = workspaceRoot();
  if (!fs.existsSync(root)) return [];
  const out: JobRecord[] = [];
  for (const id of fs.readdirSync(root)) {
    const j = loadJob(id);
    if (j) out.push(j);
  }
  out.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return out;
}

export function validateConfig(c: JobConfig): void {
  if (!c.dataset) throw new Error('dataset is required');
  if (!fs.existsSync(c.dataset)) throw new Error(`dataset not found: ${c.dataset}`);
  if (!c.description || c.description.length < 10) throw new Error('description must be at least 10 characters');
  if (!c.count || c.count < 5 || c.count > 200) throw new Error('count must be 5-200');
  if (!c.connectorId || !/^[a-zA-Z0-9]{3,128}$/.test(c.connectorId)) {
    throw new Error('connectorId must be 3-128 alphanumeric characters (no symbols)');
  }
  if (!c.connectorName) throw new Error('connectorName is required');
  if (c.mode === 'provision') {
    if (!c.auth?.tenantId) throw new Error('provision mode requires auth.tenantId');
    if (!c.auth?.clientId) throw new Error('provision mode requires auth.clientId');
    if (!c.auth.useManagedIdentity && !c.auth.clientSecretEnvVar) {
      throw new Error('provision mode requires either useManagedIdentity=true or clientSecretEnvVar');
    }
  }
  // Eval-set source: reuseEvalFromJobId and evalSetPath are mutually exclusive.
  if (c.reuseEvalFromJobId && c.evalSetPath) {
    throw new Error('reuseEvalFromJobId and evalSetPath are mutually exclusive');
  }
  if (c.evalSetPath && !fs.existsSync(c.evalSetPath)) {
    throw new Error(`evalSetPath does not exist: ${c.evalSetPath}`);
  }
  // Score configuration: judgeProvider enum and workiq->judgeAgentId.
  if (c.score?.judgeProvider) {
    const allowed = ['github-copilot', 'workiq'];
    if (!allowed.includes(c.score.judgeProvider)) {
      throw new Error(`score.judgeProvider must be one of ${allowed.join(', ')}; got '${c.score.judgeProvider}'`);
    }
    if (c.score.judgeProvider === 'workiq' && !c.score.judgeAgentId) {
      throw new Error("score.judgeAgentId is required when score.judgeProvider is 'workiq'");
    }
  }
}

/** Stable hash of a file's contents (sha256, hex, first 16 chars). */
export function fileHash(file: string): string {
  if (!fs.existsSync(file) || !fs.statSync(file).isFile()) return '';
  const h = crypto.createHash('sha256');
  const fd = fs.openSync(file, 'r');
  const buffer = Buffer.allocUnsafe(1024 * 1024);
  try {
    while (true) {
      const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, null);
      if (bytesRead === 0) break;
      h.update(buffer.subarray(0, bytesRead));
    }
  } finally {
    fs.closeSync(fd);
  }
  return h.digest('hex').slice(0, 16);
}

/** Recursive directory hash; aggregates relative path + file hash. */
export function dirHash(dir: string): string {
  if (!fs.existsSync(dir)) return '';
  if (fs.statSync(dir).isFile()) return fileHash(dir);
  const h = crypto.createHash('sha256');
  const walk = (d: string, rel: string) => {
    const entries = fs.readdirSync(d).sort();
    for (const name of entries) {
      const p = path.join(d, name);
      const r = rel ? `${rel}/${name}` : name;
      const stat = fs.statSync(p);
      if (stat.isDirectory()) walk(p, r);
      else { h.update(r); h.update(':'); h.update(fileHash(p)); h.update('\n'); }
    }
  };
  walk(dir, '');
  return h.digest('hex').slice(0, 16);
}

export function objectHash(obj: unknown): string {
  const h = crypto.createHash('sha256');
  h.update(JSON.stringify(obj, Object.keys(obj as object).sort()));
  return h.digest('hex').slice(0, 16);
}
