using Ccw.Core.Jobs;
using Ccw.Core.Models;
using Xunit;

namespace Ccw.Core.Tests.Jobs;

/// <summary>
/// Covers JobStore.ApplyConfigDefaults — the auto-generation that lets the GUI
/// present description / connectorId / connectorName as optional. Mirrors the TS
/// applyConfigDefaults tests so the two ports stay behaviourally identical.
/// </summary>
public sealed class ApplyConfigDefaultsTests
{
    private static JobConfig Base(string dataset) => new()
    {
        Dataset = dataset,
        Description = "",
        Count = 20,
        ConnectorId = "",
        ConnectorName = "",
        DeployTarget = DeployTarget.AzureFunctions,
        Mode = RunMode.Build,
        AclMode = AclMode.Everyone,
    };

    [Fact]
    public void BlankFields_AreGeneratedFromDatasetFolderName()
    {
        var result = JobStore.ApplyConfigDefaults(Base(@"C:\data\Sales_Reports"));

        Assert.Equal("Sales Reports", result.ConnectorName);
        Assert.Equal("salesreports", result.ConnectorId);
        Assert.Equal(
            "Copilot connector for the Sales Reports dataset, auto-generated by the Copilot Connector Workflow.",
            result.Description);
    }

    [Fact]
    public void TrailingSeparators_AreStrippedFromDatasetBase()
    {
        var result = JobStore.ApplyConfigDefaults(Base(@"C:\data\My-Cool.Dataset\"));

        Assert.Equal("My Cool Dataset", result.ConnectorName);
        Assert.Equal("mycooldataset", result.ConnectorId);
    }

    [Fact]
    public void ValidExplicitValues_ArePreserved()
    {
        var cfg = Base(@"C:\data\anything") with
        {
            Description = "A sufficiently long, human-written description.",
            ConnectorId = "myconnector123",
            ConnectorName = "My Connector",
        };

        var result = JobStore.ApplyConfigDefaults(cfg);

        Assert.Equal("A sufficiently long, human-written description.", result.Description);
        Assert.Equal("myconnector123", result.ConnectorId);
        Assert.Equal("My Connector", result.ConnectorName);
    }

    [Fact]
    public void ShortDescription_IsRegenerated()
    {
        var cfg = Base(@"C:\data\widgets") with
        {
            Description = "too short",
            ConnectorName = "Widgets",
            ConnectorId = "widgets",
        };

        var result = JobStore.ApplyConfigDefaults(cfg);

        Assert.Equal(
            "Copilot connector for the Widgets dataset, auto-generated by the Copilot Connector Workflow.",
            result.Description);
    }

    [Fact]
    public void MalformedConnectorId_IsSanitized_AndExplicitNamePreserved()
    {
        var cfg = Base(@"C:\data\anything") with
        {
            ConnectorId = "bad id!",
            ConnectorName = "Keep Me",
        };

        var result = JobStore.ApplyConfigDefaults(cfg);

        Assert.Equal("badid", result.ConnectorId);
        Assert.Equal("Keep Me", result.ConnectorName);
    }

    [Fact]
    public void ShortGeneratedId_GetsConnectorSuffix()
    {
        var result = JobStore.ApplyConfigDefaults(Base(@"C:\data\ab"));

        Assert.Equal("abconnector", result.ConnectorId);
        Assert.Equal("Ab", result.ConnectorName);
    }

    [Fact]
    public void EmptyDataset_FallsBackToDefaults()
    {
        var result = JobStore.ApplyConfigDefaults(Base(""));

        Assert.Equal("My Connector", result.ConnectorName);
        Assert.Equal("myconnector", result.ConnectorId);
        Assert.Equal(
            "Copilot connector for the My Connector dataset, auto-generated by the Copilot Connector Workflow.",
            result.Description);
    }
}
